### ISSUE TITLE
MapQuest API retired

### ISSUE THREAD

**Issue by joeywas** [Azimuth1/SARCAT#6]
MapQuest no longer allows direct tile access.   This broke maps used in the SARCAT app.

**Comment by JasonDalton** [comment]
We're looking for a good replacement.
MapQuest had a nice free map API that let any org get started with SARCAT without too many IT entanglements.   We're looking for a good replacement.  A good alternative would have 
- a free tier for public safety
- include aerial/satellite imagery
- contour lines for placing IPP in wilderness areas.
- allow use of the API on a private network (not a public facing app)

None of the top map APIs: Google, Bing, Here, MapBox, MapZen, etc fit these requirements.  

We're looking for a solution. I haven't checked the ESRI map tiles yet or their terms of use.  That may work out.  We'll keep you posted and thanks for bringing this up!

**Comment by joeywas** [comment]
ESRI's api works as a drop in replacement in the app/settings.json file:

http://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}

**Comment by JasonDalton** [comment]
Excellent!  We'll add that.

**Comment by JasonDalton** [comment]
Is there a topo map end point also?

**Comment by JasonDalton** [comment]
I found this in their docs:  http://services.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer/tile/4/4/4
This should work.

**Comment by joeywas** [comment]
I'll play around with that.   Want me to submit a pull request once I've made the changes?

**Comment by JasonDalton** [comment]
Great, thanks!

**Comment by JasonDalton** [comment]
We accepted PR 8, which fixed this bug.   The server demo is updated, and the version on Amazon AWS Marketplace will be updated shortly.   Thanks!
